### PR TITLE
Create Visual Studio project

### PR DESCRIPTION
**Pull request by gzili**
I have finally managed to correctly setup the Visual Studio project. Now I need all of you to confirm that you are able to import the project into Visual Studio and successfully run it.

Instructions:

1. Install "LTS" version of NodeJS from https://nodejs.org/en/ (accept the installation of additional tools and patiently wait until the script finishes even if nothing appears to be happening)
2. Open PowerShell as Administrator, run command `npm i -g npm` and wait for it to finish
3. Open Visual Studio (make sure to have installed all the required components as per lecturer's recommendations)
4. Choose "Clone a repository"
5. Fill In the URL of our repo (I hope you know how to obtain it from Github), confirm and wait for Visual Studio to open
6. Switch to this branch ("vs-setup") at the bottom right of the Visual Studio window
7. Make sure that "Solution explorer" tab is activated in the right pane
8. Double-click on "FoodSaver.sln" and make sure that the solution correctly opens (no errors anywhere)
9. Find the folder "ClientApp" in the same right pane, right-click on it and select "Open in Terminal". A command line window should appear on the bottom.
10. Run `npm i` and wait for it to finish
11. Now you should see a green play button with text "IIS Express" next to it in the top of the Visual Studio window. Click the button, wait for everything to start and after some time the UI of the app should appear in your default browser. The project terminates when you close the browser window.

If you are able to successfully finish all the steps and run the project, please approve this PR.

### CODE REVIEW

**Review by edvinasstaupas — COMMENTED** [review]
Everything works just fine, window popped out and all present features are working. Approving request

**Review by KungFur1 — APPROVED** [review]
Great work! The project works great on my end.

**Review by edvinasstaupas — APPROVED** [review]
Everything works just fine, window popped out and all present features are working. Approving request.

**Review by ago-ble — APPROVED** [review]
Everything seems fine. Ready to work!

**Pull request merged**
