### PR TITLE
Initial README Version

### PR DESCRIPTION
**Pull request by gzili**
Please check out the new README and suggest any changes as neccessary. Thank you!

### CODE REVIEW

**Comment by edvinasstaupas** [comment]
# I think everything is perfected

**Review by edvinasstaupas — COMMENTED** [review]
Everything perfected, good to go

**Comment by ago-ble** [comment]
There is no mention of what kind of program this will be. Web, mobile or so on.

**Comment by gzili** [comment]
> There is no mention of what kind of program this will be. Web, mobile or so on.

Good point. Will fix tomorrow.

**Comment by gzili** [comment]
@ago-ble Could it be in a separate "Goal" section as I think that "Vision" is more for the end user that doesn't care what type of app it is, while the "Goal" could be more related to technical development things? By the way, SPA screams WEB and it is commonly used nowadays to refer to the kind of app that we are going to build.

**Comment by ago-ble** [comment]
> @ago-ble Could it be in a separate "Goal" section as I think that "Vision" is more for the end user that doesn't care what type of app it is, while the "Goal" could be more related to technical development things? By the way, SPA screams WEB and it is commonly used nowadays to refer to the kind of app that we are going to build.

Yes, I think now everything is understandable and clear.

**Comment by gzili** [comment]
It seems like there are no more disagreements at this point, so I have merged the PR. We may make further adjustments after the progress meeting.

**Pull request merged**
